### ISSUE TITLE
offset incorrect with `bottomNavigationBar` in scaffold

### ISSUE THREAD

**Issue by antholeole** [drogel/keyboard_attachable#18] opened 2021-06-21 04:35 UTC
To reproduce: 

1. Clone the example
2. add `bottomNavigationBar: Container(height: 20,),` to the scaffold
3. observe the textbox floating 20 units above the keyboard (see screenshot)
![Screen Shot 2021-06-20 at 11 33 06 PM](https://user-images.githubusercontent.com/48811365/122707571-de47d200-d21f-11eb-8e5d-c1882f772027.png)

4. Notice that the added container is still on the bottom of the screen, where it should be - it's just for whatever reason, the `KeyboardAttachable` uses it's height (in this case, 20) to calculate it's position when the keyboard is up.

Intended behavior: 

The keyboard goes over the bottom navigation bar and the text box is still stickied above the keyboard.

This is blocking me from using this (otherwise incredibly helpful!) package. I have a footer in my app and want to use this package to solve a bug where the text box is not stickied properly.

**Comment by antholeole** [comment] 2021-06-21 05:12
I see that the problem is that the animation goes from 0 - 1, without regard for its starting height. If there'd be some way to find the widgets offset from the bottom of the screen, and then set the animation from (0 + bottom offset) to (1 - bottom offset), then you'd get a fluid transition.

Will look into this more tomorrow

**Comment by drogel** [comment] 2021-06-21 06:24
Hi @antholeole, 

Thanks for using the package and for giving such detailed description of the problem! I have indeed reproduced the unexpected behaviour, and just taking a quick look at it, I suspect it has to do with this method in the `KeyboardAttachable` widget

```dart
  void _shouldUpdateBottomSize(BuildContext context) {
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;
    if (bottomInset != 0) {
      _bottomInset = bottomInset;
    }
  }
```

The widget adds an inset to the footer based on `MediaQuery.of(context).viewInsets.bottom`. I thought that property returned the height of the soft keyboard but it looks like it is returning the height of the soft keyboard + the height of the `bottomNavigationBar`.

I will look more into it this afternoon, it should be easy to fix. Thanks!

**Comment by antholeole** [comment] 2021-06-21 17:27
Awesome - let me know if you need anything from me.

I did dive into that line of code: I may be incorrect, but I did a "print" on the value with and without the footer, and both printed the same value leading me to believe that that line of code was not the root cause.

I came to the conclusion that the issue is the starting position of the footer is 20 (the height of the container), and adding the keyboard height sets it's position to 20 + keyboard height, leaving it 20 units too high.

Again - not an expert in this domain. Just wanted to fill you in just in case this helps you.

Looking forward to the fix! Thank you!

**Comment by antholeole** [comment] 2021-06-21 17:30
Oops, didn't see your edit.

Awesome - let me know if you need anything from my end!

Looking forward to using this :)

**Comment by drogel** [comment] 2021-06-21 18:49
Hi @antholeole, 

I have just pushed some changes to a branch called [bugfix/footer-offset](https://github.com/drogel/keyboard_attachable/tree/bugfix/footer-offset) that seem to fix the bug you encountered. As you suggested in the first place, the issue was that the `KeyboardAttachable` widget was not taking into account widgets below the footer when calculating the heights and animation intervals needed for the footer to avoid the soft keyboard with a smooth transition. 

Computing the absolute position of the footer and taking its distance to the bottom of the screen into account seems to solve the issue.

I haven't released a new version of the package yet because I want to test these changes a bit more and I won't have time to do that today. I want to clean the code a bit and to test the changes on physical bezel-less iPhones. I also want to see if this approach still works when adding a `transitionBuilder` to `KeyboardAttachable`. 

You can test the changes and see if what I've done so far works for you. Any feedback appreciated!

**Comment by antholeole** [comment] 2021-06-21 20:20
That video is beautiful! It looks amazing. I defiantly will point to that branch for now and let you know if I come across any issues.

Unfortunately the only physical device I have to test against is an iPhone XR, which is a beveled device. 

Thanks for the awesome turn around time on this bugfix. This package makes development a lot easier and I'm thankful for the time you spent on it. 

Leaving the issue open, but feel free to close whenever you decide.

**Comment by drogel** [comment] 2021-07-12 18:14
Hi @antholeole,

After some more testing from my side, everything seems to work file. Since it's been 3 weeks and you have not raised any issue on the changes either, I have decided to go ahead and publish a new version of the packages that includes them.

Version 2.0.1 of `keyboard_attachable` should be publicly available now at https://pub.dev/packages/keyboard_attachable, no more weird offsets when placing widgets below the keyboard-attachable widget! 🎉 

I'm closing this issue now. Again, many thanks for raising the issue! Don't hesitate to contact me if you see any other weird behavior on my packages 😄

**Closed** 2021-07-12 18:15 UTC

**Comment by antholeole** [comment] 2021-07-12 18:44
It's been working beautifully for me on all devices. Thank you for putting in a fix so fast. I'll upgrade off of the branch tonight 😄
